let Phrases = {
    'userid': '账号',
    'password': '密码',
    'enteruserid': '请输入账号',
    'enterpassword': '请输入密码',
    'login': '登录',
    'consignmentmanagement': '代销理财',
    'enconsignmentmanagement': 'CONSIGNMENT',
    'login': '登录',
    'passwordRequired': '请输入密码',
    'useridRequired': '请输入账号',
    'invaliduser': '不合法用户',
    'goRegister': '注册新账号',
    'goResetPasswrod': '忘记密码？',
    'register': '注册',
    'resetpwd': '重置密码',
    'idcode': '验证码',
    'captcha': '验证码',
    'phoneno': '手机号',
    'password2': '确认密码',
    'enterphoneno': '请输入手机号',
    'enteridcode': '请输入验证码',
    'entercaptcha': '请输入验证码',
    'enterpassword2': '请再次输入密码',
    'phonenoRequired': '请输入手机号',
    'idcodeRequired': '请输入验证码',
    'password2Required': '请再次输入密码',
    'password2Error': '两次密码不一致请确认',
    'getidcode': '获取验证码',
    'getcaptcha': '获取验证码',
    'getcaptcha1': '再次获取',
    'phonenoInvalid': '电话号码长度不正确',
    'congratulationReg': '恭喜注册成功',
    'congratulationResetPsw': '恭喜重置密码成功',
    'goBindingCard': '绑定银行卡',
    'goBindingCard2':'继续绑定银行卡',
    'goProList': '获取理财信息',
    'personceter': '个人中心',
    'transactionDetails': '交易明细',
    'itemDetails': '持有信息',
    'signing': '存管签约',
    'cardlist': '我的银行卡',
    'entername': '请输入姓名',
    'name': '真实姓名',
    'nameRequired': '请输入姓名',
    'selcredittype': '请选择证件类型',
    'credittype': '证件类型',
    'credittypeRequired': '请选择证件类型',
    'entercreditno': '请输入证件号码',
    'creditno': '证件号码',
    'creditnoRequired': '请输入证件号码',
    'entercreditexpiredate': '请输入证件有效期',
    'creditexpiredate': '证件有效期',
    'creditexpiredateRequired': '请输入证件有效期',
    'selworktype': '请选择职业',
    'worktype': '职业',
    'worktypeRequired': '请选择职业',
    'selgender': '请选择性别',
    'gender': '性别',
    'genderRequired': '请选择性别',
    'entercompanyphone': '请输入公司电话',
    'companyphone': '公司电话',
    'enteraddr': '请输入联系地址',
    'addr': '联系地址',
    'addrRequired': '请输入联系地址',
    'next': '下一步',
    'personalinfo': '填写个人信息',
    'bankinfo': '填写银行账号',
    'complete': '完成',
    'confirm':'确认绑卡',
    'entercardno': '请输入银行卡号',
    'cardno': '银行卡号',
    'cardnoRequired': '请输入银行卡号',
    'selbank': '请选择所属银行',
    'bank': '所属银行',
    'bankRequired': '请选择所属银行',
    'entertpassword': '请输入交易密码',
    'tpassword': '交易密码',
    'tpasswordRequired': '请输入交易密码',
    'cardnoInvalid':'请输入正确银行卡号',
    'signsecu':'签约详情',
    'readTerms': '我已阅读并同意',
    'accountTermsNm': '《代销理财财富管理账户开通协议》',
    'termsRequired': '绑卡前请阅读条款',
    'back':'重填个人信息'

}

export default Phrases;