let Phrases = {
    'general': '综合',
    'profitRate': '收益',
    'term': '期限',
    'recommandProduction': '推荐产品',
    'recommandProductionSub': '收益递增 取用灵活',
    'hotProduction': '热销产品',
    'hotProductionSub': '火热发售 机不可失',
    'fieldProfitRate': '预计收益率',
    'fieldTerm': '投资期限',
    'fieldRisk': '风险等级',
    'tag-1': '抢购中',
    'tag-2': '已售罄',
    'today': '当前日期',
    'startProfitTime': '起息日期',
    'endProfitTime': '到期日期',
    'fieldMinAmount': '起售金额',
    'fieldIncreaseAmount': '递增金额',
    'fieldAvailableAmount': '可售额度',
    'amount': '购买金额',
    'buy': '购买',
    'readTerms': '本人已经阅读以上',
    'readTerms1': '，充分了解并知晓本产品的风险，愿意承担相关风险。',
    'productionTermsNm': '《产品说明书》',
    'amtRequired': '请输入金额',
    'amtLessThanMin': '金额小于起售金额',
    'amtInvalidIncrease': '递增金额不正确',
    'termsRequired': '购买前请阅读条款',
    'congratulation': '恭喜您，交易成功！',
    'fieldProdType': '产品类型',
    'backProList': '返回产品列表',
    'goLogin': '登录',
    'loginAlert': '请先登录，随后购买',
    'transConfirmAmt': '确认金额',
    'transAmt': '申购金额',
    'transType': '业务类型',
    'transResult': '交易状态',
    'transListTitle': '交易明细',
    'fieldAsset': '资产金额',
    'Holder': '持有人',
    'holdEndTime': '到期日',
    'fieldSumAmt':'您的资产总金额',
    'enterPassoword':'请输入交易密码',
    'confirm':'确认',
    'buytype':'购买方式',
    'buymethod':'交易时间内，随时购买',
    'selltype':'赎回方式',
    'sellmethod':'交易时间内，随时赎回',
    'transTime':'交易时间',
    'transPeriod':'银行工作日 (8:45-15:29)',
    'comment':'提示',
    'fieldProfitAmount':'预期收益金额',
    'startProfitTimeTag':'起息日'

}

export default Phrases;